import type {
  PhoneLine,
  RegulatoryBundle,
  CallRecord,
  AvailableNumber,
  CountryOption,
} from "@/lib/types/calling";

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000);
}

function minsAgo(mins: number) {
  return new Date(Date.now() - mins * 60 * 1000);
}

// ── Phone Lines ──────────────────────────────

export const mockPhoneLines: PhoneLine[] = [
  {
    id: "pl_001",
    number: "+1 (415) 555-0120",
    friendlyName: "Sales Main",
    country: "United States",
    countryCode: "US",
    type: "local",
    status: "active",
    assignedTo: "tm_001",
    assignedToName: "Yaseen Ahmed",
    monthlyCost: 1.15,
    config: {
      voicemailGreeting: "Thanks for calling Leadey. Leave a message and we will get back to you.",
      callForwardingNumber: "",
      callRecordingEnabled: true,
    },
    stats: { callsMade: 142, callsReceived: 89, totalMinutes: 1280, costThisMonth: 34.50 },
    createdAt: daysAgo(120),
  },
  {
    id: "pl_002",
    number: "+1 (800) 555-0199",
    friendlyName: "Inbound Toll-Free",
    country: "United States",
    countryCode: "US",
    type: "toll-free",
    status: "active",
    assignedTo: "tm_002",
    assignedToName: "Amira Johnson",
    monthlyCost: 2.15,
    config: {
      voicemailGreeting: "You have reached Leadey support. Please leave a message.",
      callForwardingNumber: "+14155550120",
      callRecordingEnabled: true,
    },
    stats: { callsMade: 56, callsReceived: 210, totalMinutes: 890, costThisMonth: 48.20 },
    createdAt: daysAgo(90),
  },
  {
    id: "pl_003",
    number: "+44 20 7946 0958",
    friendlyName: "UK Office",
    country: "United Kingdom",
    countryCode: "GB",
    type: "local",
    status: "active",
    assignedTo: "tm_003",
    assignedToName: "Lucas Park",
    monthlyCost: 1.50,
    config: {
      voicemailGreeting: "Leadey UK office. Please leave a message.",
      callForwardingNumber: "",
      callRecordingEnabled: false,
    },
    stats: { callsMade: 34, callsReceived: 18, totalMinutes: 320, costThisMonth: 12.80 },
    createdAt: daysAgo(60),
  },
  {
    id: "pl_004",
    number: "+1 (415) 555-0145",
    friendlyName: "Outbound SDR",
    country: "United States",
    countryCode: "US",
    type: "local",
    status: "suspended",
    assignedTo: null,
    assignedToName: null,
    monthlyCost: 1.15,
    config: {
      voicemailGreeting: "",
      callForwardingNumber: "",
      callRecordingEnabled: false,
    },
    stats: { callsMade: 0, callsReceived: 0, totalMinutes: 0, costThisMonth: 0 },
    createdAt: daysAgo(45),
  },
  {
    id: "pl_005",
    number: "+49 30 1234 5678",
    friendlyName: "DE Pending",
    country: "Germany",
    countryCode: "DE",
    type: "local",
    status: "pending",
    assignedTo: null,
    assignedToName: null,
    monthlyCost: 1.30,
    config: {
      voicemailGreeting: "",
      callForwardingNumber: "",
      callRecordingEnabled: false,
    },
    stats: { callsMade: 0, callsReceived: 0, totalMinutes: 0, costThisMonth: 0 },
    createdAt: daysAgo(3),
  },
];

// ── Regulatory Bundles ───────────────────────

export const mockBundles: RegulatoryBundle[] = [
  {
    id: "bun_001",
    name: "US Business Bundle",
    country: "United States",
    countryCode: "US",
    status: "twilio-approved",
    businessName: "Leadey Labs Inc.",
    businessAddress: "548 Market St, San Francisco, CA 94104",
    identityDocumentName: "EIN Certificate",
    createdAt: daysAgo(150),
  },
  {
    id: "bun_002",
    name: "UK Business Bundle",
    country: "United Kingdom",
    countryCode: "GB",
    status: "twilio-approved",
    businessName: "Leadey Labs Ltd.",
    businessAddress: "71-75 Shelton Street, London, WC2H 9JQ",
    identityDocumentName: "Company Registration",
    createdAt: daysAgo(80),
  },
  {
    id: "bun_003",
    name: "DE Business Bundle",
    country: "Germany",
    countryCode: "DE",
    status: "pending-review",
    businessName: "Leadey Labs GmbH",
    businessAddress: "Friedrichstr. 123, 10117 Berlin",
    identityDocumentName: "Handelsregister",
    createdAt: daysAgo(5),
  },
];

// ── Call Records ─────────────────────────────

export const mockCallRecords: CallRecord[] = [
  {
    id: "cr_001",
    direction: "outbound",
    from: "+1 (415) 555-0120",
    to: "+1 (650) 555-0142",
    contactName: "Sarah Mitchell",
    companyName: "Acme Corp",
    lineId: "pl_001",
    duration: 245,
    disposition: "completed",
    timestamp: minsAgo(12),
  },
  {
    id: "cr_002",
    direction: "inbound",
    from: "+1 (212) 555-0187",
    to: "+1 (800) 555-0199",
    contactName: "David Chen",
    companyName: "TechFlow Inc",
    lineId: "pl_002",
    duration: 180,
    disposition: "completed",
    timestamp: minsAgo(45),
  },
  {
    id: "cr_003",
    direction: "missed",
    from: "+1 (312) 555-0163",
    to: "+1 (415) 555-0120",
    contactName: null,
    companyName: null,
    lineId: "pl_001",
    duration: 0,
    disposition: "no-answer",
    timestamp: hoursAgo(1),
  },
  {
    id: "cr_004",
    direction: "outbound",
    from: "+1 (415) 555-0120",
    to: "+1 (408) 555-0134",
    contactName: "Emily Rodriguez",
    companyName: "DataVault Systems",
    lineId: "pl_001",
    duration: 420,
    disposition: "completed",
    timestamp: hoursAgo(2),
  },
  {
    id: "cr_005",
    direction: "outbound",
    from: "+44 20 7946 0958",
    to: "+44 20 7123 4567",
    contactName: "James Wilson",
    companyName: "CloudBridge UK",
    lineId: "pl_003",
    duration: 95,
    disposition: "completed",
    timestamp: hoursAgo(3),
  },
  {
    id: "cr_006",
    direction: "inbound",
    from: "+1 (617) 555-0176",
    to: "+1 (800) 555-0199",
    contactName: "Maria Garcia",
    companyName: "NexGen Analytics",
    lineId: "pl_002",
    duration: 0,
    disposition: "voicemail",
    timestamp: hoursAgo(4),
  },
  {
    id: "cr_007",
    direction: "outbound",
    from: "+1 (415) 555-0120",
    to: "+1 (510) 555-0198",
    contactName: "Alex Thompson",
    companyName: "Bright Metrics",
    lineId: "pl_001",
    duration: 310,
    disposition: "completed",
    timestamp: hoursAgo(5),
  },
  {
    id: "cr_008",
    direction: "missed",
    from: "+44 20 7234 5678",
    to: "+44 20 7946 0958",
    contactName: "Sophie Turner",
    companyName: "Fintech Partners",
    lineId: "pl_003",
    duration: 0,
    disposition: "no-answer",
    timestamp: hoursAgo(6),
  },
  {
    id: "cr_009",
    direction: "outbound",
    from: "+1 (800) 555-0199",
    to: "+1 (305) 555-0112",
    contactName: "Ryan Martinez",
    companyName: "SalesPro Solutions",
    lineId: "pl_002",
    duration: 0,
    disposition: "busy",
    timestamp: hoursAgo(8),
  },
  {
    id: "cr_010",
    direction: "inbound",
    from: "+1 (917) 555-0143",
    to: "+1 (415) 555-0120",
    contactName: "Lisa Park",
    companyName: "Growth Dynamics",
    lineId: "pl_001",
    duration: 560,
    disposition: "completed",
    timestamp: daysAgo(1),
  },
  {
    id: "cr_011",
    direction: "outbound",
    from: "+1 (415) 555-0120",
    to: "+1 (702) 555-0156",
    contactName: "Mark Anderson",
    companyName: "Pipeline Labs",
    lineId: "pl_001",
    duration: 145,
    disposition: "completed",
    timestamp: daysAgo(1),
  },
  {
    id: "cr_012",
    direction: "inbound",
    from: "+44 20 7345 6789",
    to: "+44 20 7946 0958",
    contactName: "Oliver Brown",
    companyName: "RevOps Europe",
    lineId: "pl_003",
    duration: 200,
    disposition: "completed",
    timestamp: daysAgo(1),
  },
  {
    id: "cr_013",
    direction: "outbound",
    from: "+1 (415) 555-0120",
    to: "+1 (480) 555-0167",
    contactName: "Jessica Lee",
    companyName: "Quantum Leads",
    lineId: "pl_001",
    duration: 0,
    disposition: "failed",
    timestamp: daysAgo(2),
  },
  {
    id: "cr_014",
    direction: "inbound",
    from: "+1 (713) 555-0189",
    to: "+1 (800) 555-0199",
    contactName: null,
    companyName: null,
    lineId: "pl_002",
    duration: 45,
    disposition: "voicemail",
    timestamp: daysAgo(2),
  },
  {
    id: "cr_015",
    direction: "outbound",
    from: "+1 (800) 555-0199",
    to: "+1 (206) 555-0134",
    contactName: "Kevin Wright",
    companyName: "Scale Venture Group",
    lineId: "pl_002",
    duration: 380,
    disposition: "completed",
    timestamp: daysAgo(3),
  },
];

// ── Available Numbers (Provision Search) ─────

export const mockAvailableNumbers: AvailableNumber[] = [
  {
    id: "an_001",
    number: "+1 (415) 555-0201",
    locality: "San Francisco",
    region: "CA",
    country: "United States",
    countryCode: "US",
    type: "local",
    monthlyCost: 1.15,
    capabilities: ["voice", "sms", "mms"],
  },
  {
    id: "an_002",
    number: "+1 (415) 555-0202",
    locality: "San Francisco",
    region: "CA",
    country: "United States",
    countryCode: "US",
    type: "local",
    monthlyCost: 1.15,
    capabilities: ["voice", "sms"],
  },
  {
    id: "an_003",
    number: "+1 (212) 555-0301",
    locality: "New York",
    region: "NY",
    country: "United States",
    countryCode: "US",
    type: "local",
    monthlyCost: 1.15,
    capabilities: ["voice", "sms", "mms"],
  },
  {
    id: "an_004",
    number: "+1 (800) 555-0301",
    locality: "Nationwide",
    region: "",
    country: "United States",
    countryCode: "US",
    type: "toll-free",
    monthlyCost: 2.15,
    capabilities: ["voice", "sms"],
  },
  {
    id: "an_005",
    number: "+1 (888) 555-0401",
    locality: "Nationwide",
    region: "",
    country: "United States",
    countryCode: "US",
    type: "toll-free",
    monthlyCost: 2.15,
    capabilities: ["voice", "sms"],
  },
  {
    id: "an_006",
    number: "+44 20 7946 1001",
    locality: "London",
    region: "England",
    country: "United Kingdom",
    countryCode: "GB",
    type: "local",
    monthlyCost: 1.50,
    capabilities: ["voice", "sms"],
  },
  {
    id: "an_007",
    number: "+44 20 7946 1002",
    locality: "London",
    region: "England",
    country: "United Kingdom",
    countryCode: "GB",
    type: "local",
    monthlyCost: 1.50,
    capabilities: ["voice"],
  },
  {
    id: "an_008",
    number: "+49 30 1234 9001",
    locality: "Berlin",
    region: "Berlin",
    country: "Germany",
    countryCode: "DE",
    type: "local",
    monthlyCost: 1.30,
    capabilities: ["voice"],
  },
  {
    id: "an_009",
    number: "+1 (415) 555-0203",
    locality: "San Francisco",
    region: "CA",
    country: "United States",
    countryCode: "US",
    type: "mobile",
    monthlyCost: 1.50,
    capabilities: ["voice", "sms", "mms"],
  },
  {
    id: "an_010",
    number: "+33 1 70 36 0001",
    locality: "Paris",
    region: "Ile-de-France",
    country: "France",
    countryCode: "FR",
    type: "local",
    monthlyCost: 1.20,
    capabilities: ["voice"],
  },
];

// ── Country Options ──────────────────────────

export const mockCountryOptions: CountryOption[] = [
  { code: "US", name: "United States", flag: "\u{1F1FA}\u{1F1F8}", availableTypes: ["local", "toll-free", "mobile"], bundleRequired: false },
  { code: "GB", name: "United Kingdom", flag: "\u{1F1EC}\u{1F1E7}", availableTypes: ["local", "mobile"], bundleRequired: true },
  { code: "CA", name: "Canada", flag: "\u{1F1E8}\u{1F1E6}", availableTypes: ["local", "toll-free"], bundleRequired: false },
  { code: "AU", name: "Australia", flag: "\u{1F1E6}\u{1F1FA}", availableTypes: ["local", "mobile"], bundleRequired: true },
  { code: "DE", name: "Germany", flag: "\u{1F1E9}\u{1F1EA}", availableTypes: ["local", "mobile"], bundleRequired: true },
  { code: "FR", name: "France", flag: "\u{1F1EB}\u{1F1F7}", availableTypes: ["local", "mobile"], bundleRequired: true },
  { code: "NL", name: "Netherlands", flag: "\u{1F1F3}\u{1F1F1}", availableTypes: ["local", "mobile"], bundleRequired: true },
  { code: "IE", name: "Ireland", flag: "\u{1F1EE}\u{1F1EA}", availableTypes: ["local"], bundleRequired: true },
  { code: "ES", name: "Spain", flag: "\u{1F1EA}\u{1F1F8}", availableTypes: ["local", "mobile"], bundleRequired: true },
  { code: "IT", name: "Italy", flag: "\u{1F1EE}\u{1F1F9}", availableTypes: ["local", "mobile"], bundleRequired: true },
];
