import type { ICPCompany } from "../types/company";

function daysAgo(d: number): Date {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000);
}

function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 60 * 60 * 1000);
}

export const mockCompanies: ICPCompany[] = [
  {
    id: "co_001",
    name: "Ramp",
    domain: "ramp.com",
    industry: "FinTech",
    employeeCount: 850,
    revenue: "$150M ARR",
    fundingStage: "Series C",
    signals: [
      { id: "cs1", type: "hiring", summary: "Posted 12 new sales positions including VP of Sales", timestamp: hoursAgo(3) },
      { id: "cs2", type: "tech_adoption", summary: "Added Outreach and Gong to tech stack", timestamp: daysAgo(2) },
    ],
    enrichmentStatus: "full",
    leadsEnriched: 18,
    leadsTotal: 67,
    relevanceScore: 95,
    discoveredAt: daysAgo(7),
    icpId: "icp_001",
  },
  {
    id: "co_002",
    name: "Clerk",
    domain: "clerk.com",
    industry: "DevTools",
    employeeCount: 180,
    revenue: "$25M ARR",
    fundingStage: "Series B",
    signals: [
      { id: "cs3", type: "funding", summary: "Raised $30M Series B led by Andreessen Horowitz", timestamp: hoursAgo(8) },
    ],
    enrichmentStatus: "partial",
    leadsEnriched: 5,
    leadsTotal: 22,
    relevanceScore: 92,
    discoveredAt: daysAgo(5),
    icpId: "icp_001",
  },
  {
    id: "co_003",
    name: "Webflow",
    domain: "webflow.com",
    industry: "SaaS",
    employeeCount: 620,
    revenue: "$100M ARR",
    fundingStage: "Series C",
    signals: [
      { id: "cs4", type: "tech_adoption", summary: "Added Salesforce, Outreach, and Gong to tech stack", timestamp: hoursAgo(12) },
      { id: "cs5", type: "hiring", summary: "3 new AE positions posted", timestamp: daysAgo(1) },
    ],
    enrichmentStatus: "pending_review",
    leadsEnriched: 0,
    leadsTotal: 45,
    relevanceScore: 88,
    discoveredAt: daysAgo(4),
    icpId: "icp_001",
  },
  {
    id: "co_004",
    name: "Postman",
    domain: "postman.com",
    industry: "DevTools",
    employeeCount: 1200,
    revenue: "$200M ARR",
    fundingStage: "Series D+",
    signals: [
      { id: "cs6", type: "intent", summary: "High research activity around sales engagement platforms", timestamp: hoursAgo(24) },
    ],
    enrichmentStatus: "not_enriched",
    leadsEnriched: 0,
    leadsTotal: 89,
    relevanceScore: 85,
    discoveredAt: daysAgo(3),
    icpId: "icp_001",
  },
  {
    id: "co_005",
    name: "Plaid",
    domain: "plaid.com",
    industry: "FinTech",
    employeeCount: 1800,
    revenue: "$350M ARR",
    fundingStage: "Series D+",
    signals: [
      { id: "cs7", type: "job_change", summary: "New CRO hired from Gong", timestamp: daysAgo(1) },
      { id: "cs8", type: "expansion", summary: "Opened new London office", timestamp: daysAgo(5) },
    ],
    enrichmentStatus: "partial",
    leadsEnriched: 8,
    leadsTotal: 120,
    relevanceScore: 90,
    discoveredAt: daysAgo(6),
    icpId: "icp_001",
  },
  {
    id: "co_006",
    name: "Neon",
    domain: "neon.tech",
    industry: "DevTools",
    employeeCount: 250,
    revenue: "$15M ARR",
    fundingStage: "Series B",
    signals: [
      { id: "cs9", type: "expansion", summary: "Opened offices in London and Singapore", timestamp: hoursAgo(48) },
    ],
    enrichmentStatus: "full",
    leadsEnriched: 12,
    leadsTotal: 18,
    relevanceScore: 78,
    discoveredAt: daysAgo(8),
    icpId: "icp_001",
  },
  {
    id: "co_007",
    name: "Resend",
    domain: "resend.com",
    industry: "DevTools",
    employeeCount: 45,
    fundingStage: "Series A",
    signals: [
      { id: "cs10", type: "news", summary: "Featured in TechCrunch for rapid growth", timestamp: daysAgo(2) },
    ],
    enrichmentStatus: "full",
    leadsEnriched: 8,
    leadsTotal: 8,
    relevanceScore: 74,
    discoveredAt: daysAgo(9),
    icpId: "icp_001",
  },
  {
    id: "co_008",
    name: "Cal.com",
    domain: "cal.com",
    industry: "SaaS",
    employeeCount: 80,
    fundingStage: "Series A",
    signals: [
      { id: "cs11", type: "social", summary: "CTO posted about needing better sales tooling", timestamp: daysAgo(3) },
    ],
    enrichmentStatus: "not_enriched",
    leadsEnriched: 0,
    leadsTotal: 12,
    relevanceScore: 70,
    discoveredAt: daysAgo(10),
    icpId: "icp_001",
  },
  {
    id: "co_009",
    name: "Acme Corp",
    domain: "acme.com",
    industry: "SaaS",
    employeeCount: 10247,
    revenue: "$500M ARR",
    fundingStage: "Series D+",
    signals: [
      { id: "cs12", type: "hiring", summary: "20+ sales roles posted, new VP RevOps position", timestamp: hoursAgo(6) },
      { id: "cs13", type: "tech_adoption", summary: "Evaluating Outreach alternatives", timestamp: daysAgo(1) },
      { id: "cs14", type: "intent", summary: "Multiple visits to sales engagement comparison pages", timestamp: daysAgo(2) },
    ],
    enrichmentStatus: "pending_review",
    leadsEnriched: 0,
    leadsTotal: 340,
    relevanceScore: 93,
    discoveredAt: daysAgo(2),
    icpId: "icp_001",
  },
  {
    id: "co_010",
    name: "Retool",
    domain: "retool.com",
    industry: "DevTools",
    employeeCount: 450,
    revenue: "$80M ARR",
    fundingStage: "Series C",
    signals: [
      { id: "cs15", type: "funding", summary: "Raised Series C, plans to triple GTM team", timestamp: daysAgo(4) },
    ],
    enrichmentStatus: "partial",
    leadsEnriched: 6,
    leadsTotal: 32,
    relevanceScore: 82,
    discoveredAt: daysAgo(5),
    icpId: "icp_001",
  },
  {
    id: "co_011",
    name: "Linear",
    domain: "linear.app",
    industry: "DevTools",
    employeeCount: 120,
    fundingStage: "Series B",
    signals: [
      { id: "cs16", type: "social", summary: "Head of Sales posted about scaling outbound", timestamp: daysAgo(3) },
    ],
    enrichmentStatus: "not_enriched",
    leadsEnriched: 0,
    leadsTotal: 15,
    relevanceScore: 68,
    discoveredAt: daysAgo(7),
    icpId: "icp_001",
  },
  {
    id: "co_012",
    name: "Vercel",
    domain: "vercel.com",
    industry: "DevTools",
    employeeCount: 550,
    revenue: "$120M ARR",
    fundingStage: "Series D+",
    signals: [
      { id: "cs17", type: "hiring", summary: "5 new sales roles posted", timestamp: daysAgo(1) },
      { id: "cs18", type: "expansion", summary: "Expanding enterprise sales team", timestamp: daysAgo(4) },
    ],
    enrichmentStatus: "full",
    leadsEnriched: 14,
    leadsTotal: 38,
    relevanceScore: 86,
    discoveredAt: daysAgo(6),
    icpId: "icp_001",
  },
  {
    id: "co_013",
    name: "Stripe",
    domain: "stripe.com",
    industry: "FinTech",
    employeeCount: 8000,
    revenue: "$14B ARR",
    fundingStage: "Public",
    signals: [
      { id: "cs19", type: "job_change", summary: "New Head of Sales hired from Datadog", timestamp: daysAgo(2) },
    ],
    enrichmentStatus: "partial",
    leadsEnriched: 12,
    leadsTotal: 280,
    relevanceScore: 87,
    discoveredAt: daysAgo(3),
    icpId: "icp_001",
  },
  {
    id: "co_014",
    name: "Supabase",
    domain: "supabase.com",
    industry: "DevTools",
    employeeCount: 200,
    fundingStage: "Series B",
    signals: [
      { id: "cs20", type: "funding", summary: "Recently raised Series B", timestamp: daysAgo(6) },
    ],
    enrichmentStatus: "not_enriched",
    leadsEnriched: 0,
    leadsTotal: 20,
    relevanceScore: 75,
    discoveredAt: daysAgo(8),
    icpId: "icp_001",
  },
  {
    id: "co_015",
    name: "Notion",
    domain: "notion.so",
    industry: "SaaS",
    employeeCount: 900,
    revenue: "$200M ARR",
    fundingStage: "Series C",
    signals: [
      { id: "cs21", type: "hiring", summary: "Director of Growth role posted", timestamp: daysAgo(3) },
      { id: "cs22", type: "intent", summary: "Team researching outbound tools", timestamp: daysAgo(5) },
    ],
    enrichmentStatus: "full",
    leadsEnriched: 16,
    leadsTotal: 55,
    relevanceScore: 84,
    discoveredAt: daysAgo(4),
    icpId: "icp_001",
  },
];
