import type { EnrichedLead } from "../types/lead";

function daysAgo(d: number): Date {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000);
}


export const mockLeads: EnrichedLead[] = [
  // === IN FUNNEL (7 leads) — enriched + assigned to a funnel ===
  { id: "lead_001", name: "Sarah Chen", title: "VP of Engineering", company: "Ramp", companyId: "co_001", department: "Engineering", seniority: "VP", email: "s.chen@ramp.com", phone: "+1 415-555-0101", linkedinUrl: "linkedin.com/in/sarachen", enrichedAt: daysAgo(3), sourceSignal: "hiring", icpId: "icp_001", location: "San Francisco, CA", status: "in_funnel", funnelId: "funnel_001" },
  { id: "lead_002", name: "Marcus Johnson", title: "Head of Sales", company: "Ramp", companyId: "co_001", department: "Sales", seniority: "VP", email: "m.johnson@ramp.com", phone: "+1 415-555-0102", linkedinUrl: "linkedin.com/in/marcusj", enrichedAt: daysAgo(3), sourceSignal: "hiring", icpId: "icp_001", location: "New York, NY", status: "in_funnel", funnelId: "funnel_001" },
  { id: "lead_006", name: "David Liu", title: "CRO", company: "Clerk", companyId: "co_002", department: "C-Suite", seniority: "C-Level", email: "d.liu@clerk.com", phone: "+1 650-555-0201", linkedinUrl: "linkedin.com/in/davidliu", enrichedAt: daysAgo(4), sourceSignal: "funding", icpId: "icp_001", location: "San Jose, CA", status: "in_funnel", funnelId: "funnel_001" },
  { id: "lead_019", name: "Amy Wu", title: "CRO", company: "Stripe", companyId: "co_013", department: "C-Suite", seniority: "C-Level", email: "a.wu@stripe.com", phone: "+1 415-555-1301", linkedinUrl: "linkedin.com/in/amywu", enrichedAt: daysAgo(2), sourceSignal: "job_change", icpId: "icp_001", location: "San Francisco, CA", status: "in_funnel", funnelId: "funnel_002" },
  { id: "lead_020", name: "Daniel Brown", title: "VP Sales", company: "Stripe", companyId: "co_013", department: "Sales", seniority: "VP", email: "d.brown@stripe.com", phone: null, linkedinUrl: "linkedin.com/in/danielbrown", enrichedAt: daysAgo(2), sourceSignal: "job_change", icpId: "icp_001", location: "Seattle, WA", status: "in_funnel", funnelId: "funnel_002" },
  { id: "lead_022", name: "Andrew Kim", title: "VP Sales", company: "Notion", companyId: "co_015", department: "Sales", seniority: "VP", email: "a.kim@notion.so", phone: "+1 415-555-1501", linkedinUrl: "linkedin.com/in/andrewkim", enrichedAt: daysAgo(3), sourceSignal: "hiring", icpId: "icp_001", location: "San Francisco, CA", status: "in_funnel", funnelId: "funnel_003" },
  { id: "lead_017", name: "Laura Martinez", title: "VP Marketing", company: "Vercel", companyId: "co_012", department: "Marketing", seniority: "VP", email: "l.martinez@vercel.com", phone: "+1 415-555-1201", linkedinUrl: "linkedin.com/in/lauramartinez", enrichedAt: daysAgo(5), sourceSignal: "hiring", icpId: "icp_001", location: "Austin, TX", status: "in_funnel", funnelId: "funnel_002" },

  // === ENRICHED (10 leads) — have email/phone, not yet in funnel ===
  { id: "lead_003", name: "Elena Rodriguez", title: "VP RevOps", company: "Ramp", companyId: "co_001", department: "RevOps", seniority: "VP", email: "e.rodriguez@ramp.com", phone: null, linkedinUrl: "linkedin.com/in/elenarodriguez", enrichedAt: daysAgo(3), sourceSignal: "hiring", icpId: "icp_001", location: "Miami, FL", status: "enriched", funnelId: null },
  { id: "lead_004", name: "James Park", title: "Director of Growth", company: "Ramp", companyId: "co_001", department: "Marketing", seniority: "Director", email: "j.park@ramp.com", phone: "+1 415-555-0104", linkedinUrl: "linkedin.com/in/jamespark", enrichedAt: daysAgo(2), sourceSignal: "tech_adoption", icpId: "icp_001", location: "San Francisco, CA", status: "enriched", funnelId: null },
  { id: "lead_007", name: "Nina Patel", title: "VP Sales", company: "Clerk", companyId: "co_002", department: "Sales", seniority: "VP", email: "n.patel@clerk.com", phone: null, linkedinUrl: "linkedin.com/in/ninapatel", enrichedAt: daysAgo(4), sourceSignal: "funding", icpId: "icp_001", location: "Boston, MA", status: "enriched", funnelId: null },
  { id: "lead_009", name: "Rachel Kim", title: "VP Sales", company: "Plaid", companyId: "co_005", department: "Sales", seniority: "VP", email: "r.kim@plaid.com", phone: "+1 415-555-0501", linkedinUrl: "linkedin.com/in/rachelkim", enrichedAt: daysAgo(5), sourceSignal: "job_change", icpId: "icp_001", location: "San Francisco, CA", status: "enriched", funnelId: null },
  { id: "lead_011", name: "Jessica Wang", title: "Director of Sales", company: "Neon", companyId: "co_006", department: "Sales", seniority: "Director", email: "j.wang@neon.tech", phone: "+1 415-555-0601", linkedinUrl: "linkedin.com/in/jessicawang", enrichedAt: daysAgo(6), sourceSignal: "expansion", icpId: "icp_001", location: "Portland, OR", status: "enriched", funnelId: null },
  { id: "lead_013", name: "Maria Santos", title: "CEO", company: "Resend", companyId: "co_007", department: "C-Suite", seniority: "C-Level", email: "m.santos@resend.com", phone: "+1 415-555-0701", linkedinUrl: "linkedin.com/in/mariasantos", enrichedAt: daysAgo(7), sourceSignal: "news", icpId: "icp_001", location: "San Francisco, CA", status: "enriched", funnelId: null },
  { id: "lead_015", name: "Sophie Lee", title: "VP Revenue", company: "Retool", companyId: "co_010", department: "Sales", seniority: "VP", email: "s.lee@retool.com", phone: "+1 415-555-1001", linkedinUrl: "linkedin.com/in/sophielee", enrichedAt: daysAgo(4), sourceSignal: "funding", icpId: "icp_001", location: "San Francisco, CA", status: "enriched", funnelId: null },
  { id: "lead_021", name: "Lisa Chang", title: "Director RevOps", company: "Stripe", companyId: "co_013", department: "RevOps", seniority: "Director", email: "l.chang@stripe.com", phone: "+1 415-555-1303", linkedinUrl: "linkedin.com/in/lisachang", enrichedAt: daysAgo(2), sourceSignal: "job_change", icpId: "icp_001", location: "San Francisco, CA", status: "enriched", funnelId: null },
  { id: "lead_025", name: "Karen Lee", title: "VP Engineering", company: "Ramp", companyId: "co_001", department: "Engineering", seniority: "VP", email: "k.lee@ramp.com", phone: null, linkedinUrl: "linkedin.com/in/karenlee", enrichedAt: daysAgo(2), sourceSignal: "hiring", icpId: "icp_001", location: "New York, NY", status: "enriched", funnelId: null },
  { id: "lead_029", name: "Tina Nguyen", title: "Director of CS", company: "Ramp", companyId: "co_001", department: "Customer Success", seniority: "Director", email: "t.nguyen@ramp.com", phone: "+1 415-555-0108", linkedinUrl: "linkedin.com/in/tinanguyen", enrichedAt: daysAgo(1), sourceSignal: "hiring", icpId: "icp_001", location: "Chicago, IL", status: "enriched", funnelId: null },

  // === ENRICHING (3 leads) — BetterContact lookup in progress ===
  { id: "lead_005", name: "Aisha Patel", title: "Sales Manager", company: "Ramp", companyId: "co_001", department: "Sales", seniority: "Manager", email: null, phone: null, linkedinUrl: "linkedin.com/in/aishapatel", enrichedAt: daysAgo(0), sourceSignal: "hiring", icpId: "icp_001", location: "Denver, CO", status: "enriching", funnelId: null },
  { id: "lead_010", name: "Tom Williams", title: "Director RevOps", company: "Plaid", companyId: "co_005", department: "RevOps", seniority: "Director", email: null, phone: null, linkedinUrl: "linkedin.com/in/tomwilliams", enrichedAt: daysAgo(0), sourceSignal: "job_change", icpId: "icp_001", location: "San Francisco, CA", status: "enriching", funnelId: null },
  { id: "lead_018", name: "Kevin Park", title: "Head of Revenue", company: "Vercel", companyId: "co_012", department: "Sales", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/kevinpark", enrichedAt: daysAgo(0), sourceSignal: "expansion", icpId: "icp_001", location: "Seattle, WA", status: "enriching", funnelId: null },

  // === DISCOVERED (10 leads from existing companies) — LinkedIn found, not yet enriched ===
  { id: "lead_008", name: "Chris Anderson", title: "Director of Marketing", company: "Clerk", companyId: "co_002", department: "Marketing", seniority: "Director", email: null, phone: null, linkedinUrl: "linkedin.com/in/chrisanderson", enrichedAt: daysAgo(3), sourceSignal: "funding", icpId: "icp_001", location: "Austin, TX", status: "discovered", funnelId: null },
  { id: "lead_012", name: "Alex Thompson", title: "Head of Growth", company: "Neon", companyId: "co_006", department: "Marketing", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/alexthompson", enrichedAt: daysAgo(6), sourceSignal: "expansion", icpId: "icp_001", location: "Portland, OR", status: "discovered", funnelId: null },
  { id: "lead_014", name: "Ryan O'Brien", title: "Sales Lead", company: "Resend", companyId: "co_007", department: "Sales", seniority: "Manager", email: null, phone: null, linkedinUrl: "linkedin.com/in/ryanobrien", enrichedAt: daysAgo(7), sourceSignal: "news", icpId: "icp_001", location: "New York, NY", status: "discovered", funnelId: null },
  { id: "lead_016", name: "Mike Chen", title: "Director of Sales", company: "Retool", companyId: "co_010", department: "Sales", seniority: "Director", email: null, phone: null, linkedinUrl: "linkedin.com/in/mikechen", enrichedAt: daysAgo(4), sourceSignal: "funding", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },
  { id: "lead_023", name: "Priya Sharma", title: "Director of Marketing", company: "Notion", companyId: "co_015", department: "Marketing", seniority: "Director", email: null, phone: null, linkedinUrl: "linkedin.com/in/priyasharma", enrichedAt: daysAgo(3), sourceSignal: "intent", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },
  { id: "lead_024", name: "Brian Foster", title: "RevOps Manager", company: "Notion", companyId: "co_015", department: "RevOps", seniority: "Manager", email: null, phone: null, linkedinUrl: "linkedin.com/in/brianfoster", enrichedAt: daysAgo(3), sourceSignal: "intent", icpId: "icp_001", location: "Los Angeles, CA", status: "discovered", funnelId: null },
  { id: "lead_026", name: "Steve Wilson", title: "Director of Sales", company: "Plaid", companyId: "co_005", department: "Sales", seniority: "Director", email: null, phone: null, linkedinUrl: "linkedin.com/in/stevewilson", enrichedAt: daysAgo(4), sourceSignal: "expansion", icpId: "icp_001", location: "Denver, CO", status: "discovered", funnelId: null },
  { id: "lead_027", name: "Michelle Yang", title: "VP Marketing", company: "Neon", companyId: "co_006", department: "Marketing", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/michelleyang", enrichedAt: daysAgo(5), sourceSignal: "expansion", icpId: "icp_001", location: "Seattle, WA", status: "discovered", funnelId: null },
  { id: "lead_028", name: "Robert Garcia", title: "Sales Manager", company: "Vercel", companyId: "co_012", department: "Sales", seniority: "Manager", email: null, phone: null, linkedinUrl: "linkedin.com/in/robertgarcia", enrichedAt: daysAgo(4), sourceSignal: "hiring", icpId: "icp_001", location: "Austin, TX", status: "discovered", funnelId: null },
  { id: "lead_030", name: "Jason Roberts", title: "VP Product", company: "Retool", companyId: "co_010", department: "Product", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/jasonroberts", enrichedAt: daysAgo(3), sourceSignal: "funding", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },

  // === NEW DISCOVERED LEADS (10 leads from new companies) ===
  { id: "lead_031", name: "Kenji Tanaka", title: "VP Engineering", company: "Postman", companyId: "co_020", department: "Engineering", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/kenjitanaka", enrichedAt: daysAgo(1), sourceSignal: "hiring", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },
  { id: "lead_032", name: "Olivia Brooks", title: "Head of Sales", company: "Postman", companyId: "co_020", department: "Sales", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/oliviabrooks", enrichedAt: daysAgo(1), sourceSignal: "hiring", icpId: "icp_001", location: "Chicago, IL", status: "discovered", funnelId: null },
  { id: "lead_033", name: "Peer Richelsen", title: "CEO", company: "Cal.com", companyId: "co_021", department: "C-Suite", seniority: "C-Level", email: null, phone: null, linkedinUrl: "linkedin.com/in/peerrichelsen", enrichedAt: daysAgo(1), sourceSignal: "funding", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },
  { id: "lead_034", name: "Bailey Pumfleet", title: "CTO", company: "Cal.com", companyId: "co_021", department: "C-Suite", seniority: "C-Level", email: null, phone: null, linkedinUrl: "linkedin.com/in/baileypumfleet", enrichedAt: daysAgo(1), sourceSignal: "funding", icpId: "icp_001", location: "Berlin, Germany", status: "discovered", funnelId: null },
  { id: "lead_035", name: "Karri Saarinen", title: "CEO", company: "Linear", companyId: "co_022", department: "C-Suite", seniority: "C-Level", email: null, phone: null, linkedinUrl: "linkedin.com/in/karrisaarinen", enrichedAt: daysAgo(2), sourceSignal: "expansion", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },
  { id: "lead_036", name: "Tuomas Artman", title: "CTO", company: "Linear", companyId: "co_022", department: "Engineering", seniority: "C-Level", email: null, phone: null, linkedinUrl: "linkedin.com/in/tuomasartman", enrichedAt: daysAgo(2), sourceSignal: "expansion", icpId: "icp_001", location: "San Francisco, CA", status: "discovered", funnelId: null },
  { id: "lead_037", name: "Jian Reis", title: "Director of Sales", company: "Linear", companyId: "co_022", department: "Sales", seniority: "Director", email: null, phone: null, linkedinUrl: "linkedin.com/in/jianreis", enrichedAt: daysAgo(2), sourceSignal: "expansion", icpId: "icp_001", location: "New York, NY", status: "discovered", funnelId: null },
  { id: "lead_038", name: "Paul Copplestone", title: "CEO", company: "Supabase", companyId: "co_023", department: "C-Suite", seniority: "C-Level", email: null, phone: null, linkedinUrl: "linkedin.com/in/paulcopplestone", enrichedAt: daysAgo(1), sourceSignal: "funding", icpId: "icp_001", location: "Singapore", status: "discovered", funnelId: null },
  { id: "lead_039", name: "Ant Wilson", title: "CTO", company: "Supabase", companyId: "co_023", department: "Engineering", seniority: "C-Level", email: null, phone: null, linkedinUrl: "linkedin.com/in/antwilson", enrichedAt: daysAgo(1), sourceSignal: "funding", icpId: "icp_001", location: "London, UK", status: "discovered", funnelId: null },
  { id: "lead_040", name: "Inian Parameshwaran", title: "VP Engineering", company: "Supabase", companyId: "co_023", department: "Engineering", seniority: "VP", email: null, phone: null, linkedinUrl: "linkedin.com/in/inianparameshwaran", enrichedAt: daysAgo(1), sourceSignal: "funding", icpId: "icp_001", location: "Melbourne, Australia", status: "discovered", funnelId: null },
];
