import type { Opportunity } from "../types/opportunity";

function daysAgo(d: number): Date {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000);
}

function daysFromNow(d: number): Date {
  return new Date(Date.now() + d * 24 * 60 * 60 * 1000);
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp_001",
    companyName: "Revolut",
    companyDomain: "revolut.com",
    contactName: "James Wright",
    contactTitle: "Head of Growth",
    contactEmail: "j.wright@revolut.com",
    stage: "negotiating",
    value: 2500,
    annualValue: 30000,
    probability: 60,
    ownerId: "tm_001",
    closeDate: daysFromNow(14),
    priority: "high",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_002",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(2),
  },
  {
    id: "opp_002",
    companyName: "PostHog",
    companyDomain: "posthog.com",
    contactName: "Alex Rivera",
    contactTitle: "Head of Growth",
    contactEmail: "a.rivera@posthog.com",
    stage: "demo_booked",
    value: 1200,
    annualValue: 14400,
    probability: 20,
    ownerId: "tm_002",
    closeDate: daysFromNow(28),
    priority: "medium",
    sourceFunnelId: "funnel_002",
    sourceLeadId: "fl_011",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "opp_003",
    companyName: "Checkout.com",
    companyDomain: "checkout.com",
    contactName: "Charlotte Taylor",
    contactTitle: "VP Revenue",
    contactEmail: "c.taylor@checkout.com",
    stage: "contract_sent",
    value: 4200,
    annualValue: 50400,
    probability: 85,
    ownerId: "tm_001",
    closeDate: daysFromNow(5),
    priority: "high",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_005",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "opp_004",
    companyName: "Raycast",
    companyDomain: "raycast.com",
    contactName: "Mia Patel",
    contactTitle: "CEO",
    contactEmail: "m.patel@raycast.com",
    stage: "demo_completed",
    value: 800,
    annualValue: 9600,
    probability: 40,
    ownerId: "tm_003",
    closeDate: daysFromNow(21),
    priority: "medium",
    sourceFunnelId: "funnel_002",
    sourceLeadId: "fl_012",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: "opp_005",
    companyName: "Monzo",
    companyDomain: "monzo.com",
    contactName: "Sarah Chen",
    contactTitle: "VP of Sales",
    contactEmail: "s.chen@monzo.com",
    stage: "won",
    value: 3500,
    annualValue: 42000,
    probability: 100,
    ownerId: "tm_001",
    closeDate: daysAgo(3),
    priority: "high",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_001",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
  },
  {
    id: "opp_006",
    companyName: "Paddle",
    companyDomain: "paddle.com",
    contactName: "Oliver Brown",
    contactTitle: "CRO",
    contactEmail: "o.brown@paddle.com",
    stage: "demo_booked",
    value: 1800,
    annualValue: 21600,
    probability: 20,
    ownerId: "tm_002",
    closeDate: daysFromNow(18),
    priority: "medium",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_004",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "opp_007",
    companyName: "Neon",
    companyDomain: "neon.tech",
    contactName: "Sophia Kim",
    contactTitle: "VP Sales",
    contactEmail: "s.kim@neon.tech",
    stage: "lost",
    value: 2200,
    annualValue: 26400,
    probability: 0,
    ownerId: "tm_003",
    closeDate: daysAgo(5),
    priority: "medium",
    sourceFunnelId: "funnel_002",
    sourceLeadId: "fl_014",
    notes: "Went with competitor - budget constraints",
    createdAt: daysAgo(22),
    updatedAt: daysAgo(5),
  },
  {
    id: "opp_008",
    companyName: "Linear",
    companyDomain: "linear.app",
    contactName: "Lucas White",
    contactTitle: "CRO",
    contactEmail: "l.white@linear.app",
    stage: "negotiating",
    value: 1500,
    annualValue: 18000,
    probability: 55,
    ownerId: "tm_001",
    closeDate: daysFromNow(10),
    priority: "medium",
    sourceFunnelId: "funnel_002",
    sourceLeadId: "fl_017",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    id: "opp_009",
    companyName: "Amplitude",
    companyDomain: "amplitude.com",
    contactName: "Ryan Park",
    contactTitle: "VP Sales",
    contactEmail: "r.park@amplitude.com",
    stage: "demo_completed",
    value: 3000,
    annualValue: 36000,
    probability: 45,
    ownerId: "tm_002",
    closeDate: daysFromNow(16),
    priority: "high",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(4),
  },
  {
    id: "opp_010",
    companyName: "Cazoo",
    companyDomain: "cazoo.co.uk",
    contactName: "Isla Roberts",
    contactTitle: "Head of Sales",
    contactEmail: "i.roberts@cazoo.co.uk",
    stage: "contract_sent",
    value: 2800,
    annualValue: 33600,
    probability: 80,
    ownerId: "tm_001",
    closeDate: daysFromNow(3),
    priority: "high",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_009",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: "opp_011",
    companyName: "GoCardless",
    companyDomain: "gocardless.com",
    contactName: "Emily Watson",
    contactTitle: "Director of Sales",
    contactEmail: "e.watson@gocardless.com",
    stage: "no_show",
    value: 1600,
    annualValue: 19200,
    probability: 5,
    ownerId: "tm_003",
    closeDate: daysFromNow(25),
    priority: "low",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_003",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
  },
  {
    id: "opp_012",
    companyName: "Railway",
    companyDomain: "railway.app",
    contactName: "Harper Davis",
    contactTitle: "CEO",
    contactEmail: "h.davis@railway.app",
    stage: "demo_booked",
    value: 600,
    annualValue: 7200,
    probability: 25,
    ownerId: "tm_002",
    closeDate: daysFromNow(30),
    priority: "low",
    sourceFunnelId: "funnel_002",
    sourceLeadId: "fl_020",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
  {
    id: "opp_013",
    companyName: "Wise",
    companyDomain: "wise.com",
    contactName: "Amelia Clarke",
    contactTitle: "Director of Marketing",
    contactEmail: "a.clarke@wise.com",
    stage: "won",
    value: 5000,
    annualValue: 60000,
    probability: 100,
    ownerId: "tm_002",
    closeDate: daysAgo(7),
    priority: "high",
    sourceFunnelId: "funnel_001",
    sourceLeadId: "fl_007",
    createdAt: daysAgo(35),
    updatedAt: daysAgo(7),
  },
  {
    id: "opp_014",
    companyName: "Airtable",
    companyDomain: "airtable.com",
    contactName: "Ben Cooper",
    contactTitle: "Head of Sales",
    contactEmail: "b.cooper@airtable.com",
    stage: "negotiating",
    value: 3800,
    annualValue: 45600,
    probability: 65,
    ownerId: "tm_001",
    closeDate: daysFromNow(12),
    priority: "high",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },
];
