import type { OrgChartPreview } from "../types/company";

export const mockOrgCharts: OrgChartPreview[] = [
  {
    companyId: "co_009",
    companyName: "Acme Corp",
    totalEmployees: 10247,
    departmentBreakdown: [
      { department: "Sales", total: 1200, cLevel: 3, vp: 12, director: 45, manager: 120, seniorIC: 280, matchesPersona: true },
      { department: "Marketing", total: 800, cLevel: 2, vp: 8, director: 32, manager: 78, seniorIC: 190, matchesPersona: true },
      { department: "Engineering", total: 4500, cLevel: 1, vp: 6, director: 28, manager: 95, seniorIC: 850, matchesPersona: false },
      { department: "Product", total: 600, cLevel: 1, vp: 4, director: 18, manager: 42, seniorIC: 110, matchesPersona: false },
      { department: "RevOps", total: 150, cLevel: 0, vp: 2, director: 8, manager: 15, seniorIC: 30, matchesPersona: true },
      { department: "Finance", total: 400, cLevel: 1, vp: 3, director: 12, manager: 35, seniorIC: 80, matchesPersona: false },
      { department: "HR", total: 300, cLevel: 1, vp: 2, director: 10, manager: 28, seniorIC: 55, matchesPersona: false },
      { department: "Customer Success", total: 500, cLevel: 1, vp: 4, director: 15, manager: 45, seniorIC: 120, matchesPersona: false },
      { department: "Operations", total: 350, cLevel: 0, vp: 3, director: 12, manager: 30, seniorIC: 70, matchesPersona: false },
    ],
    matchingCount: 67,
    estimatedCost: 67,
  },
  {
    companyId: "co_013",
    companyName: "Stripe",
    totalEmployees: 8000,
    departmentBreakdown: [
      { department: "Sales", total: 900, cLevel: 2, vp: 10, director: 35, manager: 90, seniorIC: 220, matchesPersona: true },
      { department: "Marketing", total: 650, cLevel: 1, vp: 6, director: 24, manager: 60, seniorIC: 150, matchesPersona: true },
      { department: "Engineering", total: 3800, cLevel: 1, vp: 8, director: 32, manager: 110, seniorIC: 900, matchesPersona: false },
      { department: "Product", total: 500, cLevel: 1, vp: 4, director: 16, manager: 40, seniorIC: 95, matchesPersona: false },
      { department: "RevOps", total: 120, cLevel: 0, vp: 2, director: 6, manager: 12, seniorIC: 25, matchesPersona: true },
      { department: "Finance", total: 450, cLevel: 1, vp: 4, director: 14, manager: 38, seniorIC: 85, matchesPersona: false },
    ],
    matchingCount: 52,
    estimatedCost: 52,
  },
  {
    companyId: "co_004",
    companyName: "Postman",
    totalEmployees: 1200,
    departmentBreakdown: [
      { department: "Sales", total: 200, cLevel: 1, vp: 3, director: 10, manager: 25, seniorIC: 55, matchesPersona: true },
      { department: "Marketing", total: 120, cLevel: 1, vp: 2, director: 8, manager: 18, seniorIC: 35, matchesPersona: true },
      { department: "Engineering", total: 550, cLevel: 1, vp: 3, director: 12, manager: 40, seniorIC: 150, matchesPersona: false },
      { department: "Product", total: 100, cLevel: 0, vp: 2, director: 6, manager: 12, seniorIC: 28, matchesPersona: false },
      { department: "RevOps", total: 30, cLevel: 0, vp: 1, director: 3, manager: 6, seniorIC: 10, matchesPersona: true },
    ],
    matchingCount: 24,
    estimatedCost: 24,
  },
  {
    companyId: "co_005",
    companyName: "Plaid",
    totalEmployees: 1800,
    departmentBreakdown: [
      { department: "Sales", total: 280, cLevel: 1, vp: 4, director: 14, manager: 35, seniorIC: 70, matchesPersona: true },
      { department: "Marketing", total: 180, cLevel: 1, vp: 3, director: 10, manager: 22, seniorIC: 45, matchesPersona: true },
      { department: "Engineering", total: 800, cLevel: 1, vp: 4, director: 18, manager: 55, seniorIC: 200, matchesPersona: false },
      { department: "Product", total: 150, cLevel: 1, vp: 2, director: 8, manager: 18, seniorIC: 40, matchesPersona: false },
      { department: "RevOps", total: 45, cLevel: 0, vp: 1, director: 4, manager: 8, seniorIC: 15, matchesPersona: true },
    ],
    matchingCount: 32,
    estimatedCost: 32,
  },
  {
    companyId: "co_015",
    companyName: "Notion",
    totalEmployees: 900,
    departmentBreakdown: [
      { department: "Sales", total: 150, cLevel: 1, vp: 3, director: 8, manager: 20, seniorIC: 40, matchesPersona: true },
      { department: "Marketing", total: 100, cLevel: 1, vp: 2, director: 6, manager: 14, seniorIC: 30, matchesPersona: true },
      { department: "Engineering", total: 400, cLevel: 1, vp: 3, director: 12, manager: 35, seniorIC: 110, matchesPersona: false },
      { department: "Product", total: 80, cLevel: 0, vp: 2, director: 5, manager: 10, seniorIC: 22, matchesPersona: false },
      { department: "RevOps", total: 25, cLevel: 0, vp: 1, director: 3, manager: 5, seniorIC: 8, matchesPersona: true },
    ],
    matchingCount: 19,
    estimatedCost: 19,
  },
];
