import type { ScraperDefinition, ScraperAssignment } from "../types/scraper";

export const scraperCatalog: ScraperDefinition[] = [
  {
    id: "scraper_job_board",
    name: "Job Board Monitor",
    description: "Monitors LinkedIn Jobs, Indeed, Greenhouse, and Lever for hiring signals that indicate company growth",
    icon: "Briefcase",
    category: "jobs",
    signalTypes: ["hiring"],
    sourceIds: ["linkedin", "indeed", "glassdoor", "greenhouse", "lever"],
    frequencyOptions: ["daily", "weekly"],
    creditCostPerRun: 2,
    tier: "basic",
  },
  {
    id: "scraper_funding",
    name: "Funding Tracker",
    description: "Tracks Crunchbase, PitchBook, and press releases for funding rounds and financial events",
    icon: "DollarSign",
    category: "funding",
    signalTypes: ["funding"],
    sourceIds: ["crunchbase", "pitchbook", "google_news", "techcrunch"],
    frequencyOptions: ["daily", "weekly"],
    creditCostPerRun: 1,
    tier: "basic",
  },
  {
    id: "scraper_tech_stack",
    name: "Tech Stack Monitor",
    description: "Analyzes BuiltWith, Wappalyzer, and G2 data to detect technology adoption changes",
    icon: "Cpu",
    category: "tech",
    signalTypes: ["tech_adoption"],
    sourceIds: ["builtwith", "wappalyzer", "g2"],
    frequencyOptions: ["daily", "weekly"],
    creditCostPerRun: 3,
    tier: "pro",
  },
  {
    id: "scraper_intent",
    name: "Intent Signal Monitor",
    description: "Detects research activity, review site visits, and content consumption patterns",
    icon: "Search",
    category: "intent",
    signalTypes: ["intent"],
    sourceIds: ["g2", "reddit", "x", "google_news"],
    frequencyOptions: ["hourly", "daily"],
    creditCostPerRun: 5,
    tier: "enterprise",
  },
  {
    id: "scraper_social",
    name: "Social Listener",
    description: "Monitors LinkedIn posts, Twitter/X activity, and engagement patterns from key decision makers",
    icon: "MessageCircle",
    category: "social",
    signalTypes: ["social"],
    sourceIds: ["linkedin", "x", "reddit"],
    frequencyOptions: ["daily", "weekly"],
    creditCostPerRun: 1,
    tier: "basic",
  },
  {
    id: "scraper_news",
    name: "News & PR Monitor",
    description: "Scans Google News, TechCrunch, and company newsrooms for relevant announcements",
    icon: "Newspaper",
    category: "news",
    signalTypes: ["news"],
    sourceIds: ["google_news", "techcrunch", "reddit", "x"],
    frequencyOptions: ["daily", "weekly"],
    creditCostPerRun: 1,
    tier: "basic",
  },
  {
    id: "scraper_linkedin_changes",
    name: "LinkedIn Change Tracker",
    description: "Tracks new hires, departures, and promotions at target companies via LinkedIn",
    icon: "UserCheck",
    category: "people",
    signalTypes: ["job_change"],
    sourceIds: ["linkedin", "x"],
    frequencyOptions: ["daily", "weekly"],
    creditCostPerRun: 2,
    tier: "pro",
  },
  {
    id: "scraper_traffic",
    name: "Web Traffic Estimator",
    description: "Monitors SimilarWeb-style traffic trends and growth patterns for target domains",
    icon: "TrendingUp",
    category: "traffic",
    signalTypes: ["expansion"],
    sourceIds: ["google_news", "techcrunch", "reddit"],
    frequencyOptions: ["weekly"],
    creditCostPerRun: 4,
    tier: "enterprise",
  },
];

function daysAgo(d: number): Date {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000);
}

function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 60 * 60 * 1000);
}

export const mockScraperAssignments: ScraperAssignment[] = [
  {
    id: "sa_001",
    scraperId: "scraper_job_board",
    scraperName: "Job Board Monitor",
    icpId: "icp_001",
    enabled: true,
    frequency: "daily",
    configuredAt: daysAgo(12),
    lastRun: hoursAgo(3),
    creditsPerRun: 2,
    status: "completed",
    signalsFound: 34,
    companiesFound: 18,
    keywords: ["SDR", "Account Executive", "Sales Engineer"],
    excludedKeywords: ["intern", "contract"],
    keywordMatchMode: "any",
    countries: ["United States", "Canada"],
    languages: ["English"],
    sourceIds: ["linkedin", "indeed", "glassdoor", "greenhouse"],
    sourceSignalLimits: {
      linkedin: 40,
      indeed: 30,
      glassdoor: 25,
      greenhouse: 25,
    },
    lookbackDays: 7,
    maxSignalsPerRun: 120,
    minSignalScore: 72,
    onlyDecisionMakers: false,
    dedupeCompanies: true,
    includeRemoteRoles: true,
    notifyOnHighIntent: true,
  },
  {
    id: "sa_002",
    scraperId: "scraper_funding",
    scraperName: "Funding Tracker",
    icpId: "icp_001",
    enabled: true,
    frequency: "daily",
    configuredAt: daysAgo(12),
    lastRun: hoursAgo(1),
    creditsPerRun: 1,
    status: "running",
    signalsFound: 12,
    companiesFound: 8,
    keywords: ["Series A", "Series B", "growth round"],
    excludedKeywords: ["bridge round", "grant"],
    keywordMatchMode: "all",
    countries: ["United States", "Canada"],
    languages: ["English"],
    sourceIds: ["crunchbase", "pitchbook", "google_news", "techcrunch"],
    sourceSignalLimits: {
      crunchbase: 25,
      pitchbook: 20,
      google_news: 20,
      techcrunch: 15,
    },
    lookbackDays: 14,
    maxSignalsPerRun: 80,
    minSignalScore: 75,
    onlyDecisionMakers: true,
    dedupeCompanies: true,
    includeRemoteRoles: false,
    notifyOnHighIntent: true,
  },
  {
    id: "sa_003",
    scraperId: "scraper_tech_stack",
    scraperName: "Tech Stack Monitor",
    icpId: "icp_001",
    enabled: true,
    frequency: "weekly",
    configuredAt: daysAgo(10),
    lastRun: daysAgo(2),
    creditsPerRun: 3,
    status: "completed",
    signalsFound: 21,
    companiesFound: 14,
    keywords: ["Salesforce", "HubSpot", "Outreach"],
    excludedKeywords: ["wordpress", "shopify"],
    keywordMatchMode: "any",
    countries: ["United States", "United Kingdom", "Germany"],
    languages: ["English"],
    sourceIds: ["builtwith", "wappalyzer", "g2"],
    sourceSignalLimits: {
      builtwith: 20,
      wappalyzer: 20,
      g2: 20,
    },
    lookbackDays: 30,
    maxSignalsPerRun: 60,
    minSignalScore: 70,
    onlyDecisionMakers: false,
    dedupeCompanies: true,
    includeRemoteRoles: false,
    notifyOnHighIntent: false,
  },
  {
    id: "sa_004",
    scraperId: "scraper_social",
    scraperName: "Social Listener",
    icpId: "icp_001",
    enabled: true,
    frequency: "daily",
    configuredAt: daysAgo(8),
    lastRun: hoursAgo(6),
    creditsPerRun: 1,
    status: "idle",
    signalsFound: 8,
    companiesFound: 6,
    keywords: ["outbound sales", "signal-based selling"],
    excludedKeywords: ["job seeker", "freelancer"],
    keywordMatchMode: "any",
    countries: ["United States", "United Kingdom"],
    languages: ["English"],
    sourceIds: ["linkedin", "x", "reddit"],
    sourceSignalLimits: {
      linkedin: 60,
      x: 40,
      reddit: 40,
    },
    lookbackDays: 5,
    maxSignalsPerRun: 140,
    minSignalScore: 68,
    onlyDecisionMakers: true,
    dedupeCompanies: true,
    includeRemoteRoles: false,
    notifyOnHighIntent: true,
  },
  {
    id: "sa_005",
    scraperId: "scraper_linkedin_changes",
    scraperName: "LinkedIn Change Tracker",
    icpId: "icp_001",
    enabled: false,
    frequency: "daily",
    configuredAt: daysAgo(5),
    lastRun: daysAgo(3),
    creditsPerRun: 2,
    status: "idle",
    signalsFound: 5,
    companiesFound: 4,
    keywords: ["VP Sales", "CRO", "Head of Revenue"],
    excludedKeywords: ["advisor", "consultant"],
    keywordMatchMode: "all",
    countries: ["United States"],
    languages: ["English"],
    sourceIds: ["linkedin", "x"],
    sourceSignalLimits: {
      linkedin: 45,
      x: 45,
    },
    lookbackDays: 10,
    maxSignalsPerRun: 90,
    minSignalScore: 80,
    onlyDecisionMakers: true,
    dedupeCompanies: true,
    includeRemoteRoles: false,
    notifyOnHighIntent: true,
  },
];
